### ISSUE TITLE
Posts#owed hidden doesn't order posts

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#975] opened 2018-12-20 01:30 UTC
Currently, looking at your list of hidden "owed" posts doesn't order the posts, resulting in arbitrary database order.

**Comment by teceler** [comment] 2018-12-20 01:33
Duplicate of #871

**Comment by Throne3d** [comment] 2018-12-20 01:36
Actually, these issues are distinct. Reopening.

**Closed** 2019-01-05 06:53 UTC
