### ISSUE TITLE
Change private messages to not use the .post-screenname selector

### ISSUE THREAD

**Issue by teceler** [Marri/glowfic#843] opened 2018-07-03 23:49 UTC
A mixin can probably be used for common components, and that would avoid needing some ugly hacks we currently are using to work around this.

(see `.post-screenname, .post-screenname a, .post-screenname a:visited` selector in starries, for example)

**Comment by Throne3d** [comment] 2018-07-06 04:05
Yeah, semantically this is currently incorrect. Fixing it – and thereby unifying, more accurately, the parts in common between the message and reply interfaces – would be good.

**Comment by Marri** [comment] 2018-11-26 09:53
Duplicate of #580

**Closed by Marri** 2018-11-26 09:53 UTC
Labels: 3. medium priority, 7. easy, dev, type: bug
