### ISSUE TITLE
Put pagination on continuities with long subsections

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#802] opened 2018-05-08 21:15 UTC
I can't see an issue for this, but it was reported before. Some continuities have very long subsections, and these don't currently paginate, meaning some threads are hidden. We should come up with some way to present this information to the user and let them navigate the long sections.

One way we could do this is by presenting paginators at the relevant sections, and then using the `page` parameter on board#show to control all the subsection's pages, but I think that would be ugly.
Another way would be, in cases of sections that are long, to present the information _that_ they're long (so you can click through to them and see the paginator), and also to come up with some way to show the later pages of a continuity in the case that the unsectioned posts number more than 25.

**Comment by Marri** [comment] 2018-11-26 11:03
Duplicate of #178

**Closed by Marri** 2018-11-26 11:03 UTC
Labels: 1. critical, 8. medium, good first issue, type: bug
