### ISSUE TITLE
Add a proper utility for splitting threads

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#620] opened 2017-12-16 23:03 UTC
https://github.com/Marri/glowfic/commit/fa81586135b9c6eeef196c595d2c9196be77e806 adds a bit but it should be properly integrated and tested. This could then be exposed to users to allow them to split posts themselves.

**Comment by Marri** [comment] 2018-11-26 09:55
Duplicate of #574

**Closed by Marri** 2018-11-26 09:55 UTC
Labels: 3. medium priority, 8. medium, dev, type: new feature
